services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"
    restart: always
    env_file:
      - .env.public
    environment:
      - DATABASE_HOST=database
    command: >
      sh -c 'python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver ${DJANGO_SERVER_HOST}:${DJANGO_SERVER_PORT}'
    ports:
      - 8001:${DJANGO_SERVER_PORT}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.4
    container_name: "database"
    restart: always
    env_file:
      - .env.public
    ports:
      - 5433:${DATABASE_PORT}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
    driver: local
